In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("../data/raw/supply_chain_dataset1.csv")

# Display first 5 rows
df.head()

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

In [2]:
df.shape

(91250, 15)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91250 entries, 0 to 91249
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     91250 non-null  str
 1   SKU_ID                   91250 non-null  str
 2   Warehouse_ID             91250 non-null  str
 3   Supplier_ID              91250 non-null  str
 4   Region                   91250 non-null  str
 5   Units_Sold               91250 non-null  int64
 6   Inventory_Level          91250 non-null  int64
 7   Supplier_Lead_Time_Days  91250 non-null  int64
 8   Reorder_Point            91250 non-null  int64
 9   Order_Quantity           91250 non-null  int64
 10  Unit_Cost                91250 non-null  float64
 11  Unit_Price               91250 non-null  float64
 12  Promotion_Flag           91250 non-null  int64
 13  Stockout_Flag            91250 non-null  int64
 14  Demand_Forecast          91250 non-null  float64
dtypes: float64(3), int64(7), str(5)
memory usage: 13.0 MB

In [4]:
df.columns

Index(['Date', 'SKU_ID', 'Warehouse_ID', 'Supplier_ID', 'Region', 'Units_Sold',
       'Inventory_Level', 'Supplier_Lead_Time_Days', 'Reorder_Point',
       'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Promotion_Flag',
       'Stockout_Flag', 'Demand_Forecast'],
      dtype='str')

In [5]:
df.describe()

,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
count,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.0,91250.000000
mean,20.054564,471.522312,7.984000,300.068000,19.272493,12.203320,18.261800,0.101589,0.0,20.082033
std,9.068602,133.488002,3.907929,54.879945,82.340831,4.574982,7.121136,0.302109,0.0,9.503955
min,0.000000,168.000000,2.000000,201.000000,0.000000,5.020000,6.950000,0.000000,0.0,0.000000
25%,13.000000,370.000000,4.000000,252.000000,0.000000,8.180000,12.000000,0.000000,0.0,12.950000
50%,20.000000,461.000000,8.000000,300.000000,0.000000,11.990000,18.180000,0.000000,0.0,19.950000
75%,27.000000,564.000000,11.000000,346.000000,0.000000,16.320000,23.390000,0.000000,0.0,26.930000
max,59.000000,990.000000,14.000000,398.000000,499.000000,19.760000,35.100000,1.000000,0.0,61.420000

In [6]:
df.isnull().sum()

Date                       0
SKU_ID                     0
Warehouse_ID               0
Supplier_ID                0
Region                     0
Units_Sold                 0
Inventory_Level            0
Supplier_Lead_Time_Days    0
Reorder_Point              0
Order_Quantity             0
Unit_Cost                  0
Unit_Price                 0
Promotion_Flag             0
Stockout_Flag              0
Demand_Forecast            0
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
print("SKUs:", df["SKU_ID"].nunique())
print("Warehouses:", df["Warehouse_ID"].nunique())
print("Suppliers:", df["Supplier_ID"].nunique())
print("Regions:", df["Region"].nunique())

SKUs: 50
Warehouses: 5
Suppliers: 10
Regions: 4

In [10]:
print(df["Promotion_Flag"].value_counts())
print(df["Stockout_Flag"].value_counts())

Promotion_Flag
0    81980
1     9270
Name: count, dtype: int64
Stockout_Flag
0    91250
Name: count, dtype: int64

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

print("Start date:", df["Date"].min())
print("End date:", df["Date"].max())

Start date: 2024-01-01 00:00:00
End date: 2024-12-30 00:00:00

In [12]:
df["Date"].nunique()

365

In [13]:
df.dtypes

Date                       datetime64[us]
SKU_ID                                str
Warehouse_ID                          str
Supplier_ID                           str
Region                                str
Units_Sold                          int64
Inventory_Level                     int64
Supplier_Lead_Time_Days             int64
Reorder_Point                       int64
Order_Quantity                      int64
Unit_Cost                         float64
Unit_Price                        float64
Promotion_Flag                      int64
Stockout_Flag                       int64
Demand_Forecast                   float64
dtype: object

In [14]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.duplicated(
    subset=["Date", "SKU_ID", "Warehouse_ID"]
).sum()

np.int64(0)

In [17]:
numeric_columns = [
    "Units_Sold",
    "Inventory_Level",
    "Supplier_Lead_Time_Days",
    "Reorder_Point",
    "Order_Quantity",
    "Unit_Cost",
    "Unit_Price",
    "Demand_Forecast"
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Units_Sold,91250.0,20.054564,9.068602,0.00,13.00,20.00,27.00,59.00
Inventory_Level,91250.0,471.522312,133.488002,168.00,370.00,461.00,564.00,990.00
Supplier_Lead_Time_Days,91250.0,7.984000,3.907929,2.00,4.00,8.00,11.00,14.00
Reorder_Point,91250.0,300.068000,54.879945,201.00,252.00,300.00,346.00,398.00
Order_Quantity,91250.0,19.272493,82.340831,0.00,0.00,0.00,0.00,499.00
Unit_Cost,91250.0,12.203320,4.574982,5.02,8.18,11.99,16.32,19.76
Unit_Price,91250.0,18.261800,7.121136,6.95,12.00,18.18,23.39,35.10
Demand_Forecast,91250.0,20.082033,9.503955,0.00,12.95,19.95,26.93,61.42

In [18]:
for col in numeric_columns:
    print(col, "negative values:", (df[col] < 0).sum())

Units_Sold negative values: 0
Inventory_Level negative values: 0
Supplier_Lead_Time_Days negative values: 0
Reorder_Point negative values: 0
Order_Quantity negative values: 0
Unit_Cost negative values: 0
Unit_Price negative values: 0
Demand_Forecast negative values: 0

In [19]:
(df["Unit_Price"] < 0).sum()

np.int64(0)

In [20]:
(df["Unit_Cost"] < 0).sum()

np.int64(0)

In [21]:
(df["Inventory_Level"] < 0).sum()

np.int64(0)

In [22]:
(df["Units_Sold"] < 0).sum()

np.int64(0)

In [23]:
(df["Supplier_Lead_Time_Days"] < 0).sum()

np.int64(0)

In [24]:
print(df["Region"].unique())
print(df["Promotion_Flag"].unique())
print(df["Stockout_Flag"].unique())

<ArrowStringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str
[0 1]
[0]

In [25]:
df["Region"].value_counts()

Region
North    22974
East     22934
South    22720
West     22622
Name: count, dtype: int64

In [26]:
df["Promotion_Flag"].value_counts()

Promotion_Flag
0    81980
1     9270
Name: count, dtype: int64

In [27]:
df["Stockout_Flag"].value_counts()

Stockout_Flag
0    91250
Name: count, dtype: int64

In [29]:
df["Reorder_Risk"] = np.where(
    df["Inventory_Level"] <= df["Reorder_Point"],
    "Reorder Required",
    "Sufficient Stock"
)

In [30]:
df["Reorder_Risk"].value_counts()

Reorder_Risk
Sufficient Stock    86209
Reorder Required     5041
Name: count, dtype: int64

In [31]:
df["Reorder_Risk"].value_counts(normalize=True) * 100

Reorder_Risk
Sufficient Stock    94.475616
Reorder Required     5.524384
Name: proportion, dtype: float64

In [32]:
df["Inventory_Value"] = (
    df["Inventory_Level"] * df["Unit_Cost"]
)

In [33]:
df["Inventory_Sales_Value"] = (
    df["Inventory_Level"] * df["Unit_Price"]
)

In [34]:
df["Gross_Margin_Per_Unit"] = (
    df["Unit_Price"] - df["Unit_Cost"]
)

In [35]:
df["Gross_Margin_Percentage"] = (
    df["Gross_Margin_Per_Unit"] / df["Unit_Price"] * 100
)

In [36]:
df["Days_of_Inventory"] = np.where(
    df["Demand_Forecast"] > 0,
    df["Inventory_Level"] / df["Demand_Forecast"],
    np.nan
)

In [37]:
df["Inventory_Status"] = np.select(
    [
        df["Days_of_Inventory"] < 7,
        df["Days_of_Inventory"].between(7, 30),
        df["Days_of_Inventory"] > 30
    ],
    [
        "High Risk",
        "Healthy",
        "Overstock"
    ],
    default="Unknown"
)

In [40]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

output_path = "../data/cleaned/supply_chain_cleaned.csv"

df.to_csv(output_path, index=False)

print("Saved:", output_path)

Saved: ../data/cleaned/supply_chain_cleaned.csv

In [41]:
df["Inventory_Status"] = np.select(
    [
        df["Demand_Forecast"] == 0,
        df["Days_of_Inventory"] < 7,
        df["Days_of_Inventory"].between(7, 30),
        df["Days_of_Inventory"] > 30
    ],
    [
        "No Forecast Demand",
        "High Risk",
        "Healthy",
        "Overstock"
    ],
    default="Unknown"
)

In [42]:
df["Inventory_Status"].value_counts()

Inventory_Status
Healthy               57857
Overstock             31782
No Forecast Demand      892
High Risk               719
Name: count, dtype: int64

In [43]:
df.to_csv(
    "../data/cleaned/supply_chain_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.